# NumPy

Numpy is a linear algebra library for python. Almost all the libraries in PyData ecosysystem reply on Numpy.

Numpy is a fundamental package for scientific computing in python. It provides:
- multidimentional array object
- various derived objects (such as masked arrays and matrices)
- various operations on array for fast outcomes (such as sorting, shaping, mathematical and operations etc.)

In [1]:
# considering numpy is pre installed, let's import numpy library at first

import numpy as np

## Numpy Arrays

We will mainly use numpy arrays to create arrays in numpy. Numpy arrays are essentially of two types: 
- Vectors (Vectors are strictly 1-D array)
- Matrices (Matrices are 2-D array)


### Creating Numpy Arrays

#### From Python List

In [2]:
score = [0,3,4,2,1]

In [3]:
ar_1 = np.array(score)

In [4]:
ar_1

array([0, 3, 4, 2, 1])

In [8]:
#creating matrix
score_mat = [[0,2,1],[3,4,6]]
score_mat

[[0, 2, 1], [3, 4, 6]]

In [9]:
np.array(score_mat)

array([[0, 2, 1],
       [3, 4, 6]])

### Built-In Methods

#### arange
Return evenly spaced values between a given range

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#we can add a step in arange 
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
new_array = np.arange(0,20,3)
new_array

array([ 0,  3,  6,  9, 12, 15, 18])

### Zeros and Ones

Generate arrays of zeros and ones

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [27]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### eye
Creates an identity matrix

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(5) * 4

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

### Random

#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over (0, 1).


In [34]:
np.random.rand(4)

array([0.8530994 , 0.47821909, 0.70641624, 0.76730117])

In [35]:
np.random.rand(4,3)

array([[0.01060008, 0.91731608, 0.92949408],
       [0.33750088, 0.1184742 , 0.91699374],
       [0.52094789, 0.8998757 , 0.71873362],
       [0.65542988, 0.15994216, 0.95402   ]])

### randn
returns a sample or samples from 'satndard normal distribution' unlike rand which returns uniform distribution

In [37]:
np.random.randn(4)

array([-0.17717065, -0.36883026, -1.43970421,  0.19236119])

In [38]:
np.random.randn(4,3)

array([[-0.63606542,  2.0828409 ,  1.1426802 ],
       [ 1.01863562, -0.85450002,  1.3652764 ],
       [-0.91611089, -0.24823997, -1.82124494],
       [ 1.1707394 ,  2.06114297, -0.06035173]])

### randint

returns random integer from a range low(inclusive) to high(exclusive)

In [40]:
np.random.randint(0,101)

60

In [41]:
np.random.randint(0,101,10)

array([40, 31, 68, 94, 82, 84, 35, 44, 16, 61])

### Array Attributes and Methods


In [42]:
nparr = np.arange(25)
ranarr = np.random.randint(0,50,20)

In [43]:
nparr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr

array([32,  1, 48, 41, 26, 20, 32, 12, 36, 38, 14, 39, 43, 13, 35, 34, 41,
        0, 20, 10])

### Reshape

reshapes the array. returns same array with new shape

In [45]:
nparr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.reshape(4,5)

array([[32,  1, 48, 41, 26],
       [20, 32, 12, 36, 38],
       [14, 39, 43, 13, 35],
       [34, 41,  0, 20, 10]])

In [49]:
ranarr.reshape(10,2)

array([[32,  1],
       [48, 41],
       [26, 20],
       [32, 12],
       [36, 38],
       [14, 39],
       [43, 13],
       [35, 34],
       [41,  0],
       [20, 10]])

### min,max,argmin,argmax

These methods are used to finding min and max value in an array. Or to find the index locations using argmin and argmax 

In [55]:
nparr.min()

0

In [56]:
nparr.max()

24

In [58]:
ranarr.max()

48

In [59]:
ranarr.argmax()

2

In [60]:
#just to check the array
ranarr

array([32,  1, 48, 41, 26, 20, 32, 12, 36, 38, 14, 39, 43, 13, 35, 34, 41,
        0, 20, 10])

In [62]:
ranarr.argmin()

17

### Shape
tells no. of attributes an array have (not a method)

In [63]:
ranarr.shape

(20,)

In [64]:
nparr.shape

(25,)

In [65]:
new_nparr = nparr.reshape(5,5)
new_nparr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
new_nparr.shape

(5, 5)

### dtype
tells the data type of the object in an array

In [67]:
nparr.dtype

dtype('int32')

In [68]:
ranarr.dtype

dtype('int32')

## Numpy Indexing and Selection



In [71]:
in_arr = np.arange(20,30)
in_arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Bracket Indexing and Selection

In [73]:
#get the value at an index
in_arr[3]

23

In [76]:
#get values in a range
in_arr[3:7]

#Note that it will include the element at first position and exclude the last element of the range

array([23, 24, 25, 26])

### Broadcasting

Numpy arrays habe the ability to broadcast unline python lists which don't have this feature

In [77]:
# setting a value with index range

in_arr[1:4] = 0

In [78]:
in_arr

array([20,  0,  0,  0, 24, 25, 26, 27, 28, 29])

One thing must be noted that the broadcast change has been made to original array as well. It is done to avoid memory issues. if we want our original array to stay intact, then we should make a copy of the original array and then broadcast in the copy of array.

In [79]:
in_arr[:7]

array([20,  0,  0,  0, 24, 25, 26])

In [80]:
in_arr[5:]

array([25, 26, 27, 28, 29])

We will try making copy of an array and do the slicing on the copy of the array

In [84]:
my_arr = np.arange(0,11)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
my_arr_copy = my_arr.copy()
my_arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
my_arr_copy[0:5] = 50
my_arr_copy

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [89]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

we can see that the original array remained unchanged and slicing only changed the copy of the array

### Indexing 2D arrays (matrices)

In [94]:
new_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
#slicing portion of array

new_arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [108]:
large_arr = np.arange(0,100).reshape(10,10)
large_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
large_arr[4:7,3:7]

array([[43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66]])

In [114]:
large_arr[3:4,7:8]

array([[37]])

### Selection

In [116]:
select_arr = np.arange(0,11)
select_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
select_arr[:5] = 100
select_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [120]:
select_arr < 100

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [122]:
select_arr[select_arr < 100]

array([ 5,  6,  7,  8,  9, 10])

By the above method select_arr will only return the value of the elements and not boolen value of the array i.e. True or False

## Numpy Operations
### Arithmatic

We can easily perform normal arithmatic operations on arrays

In [125]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
#addition

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [127]:
#subtraction 

arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
# multiplication

arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
#division
# we get warning but not an error. note nan value 
arr / arr

C:\Users\MANISH~1\AppData\Local\Temp/ipykernel_4264/2442522582.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [131]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [132]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### Universal Array Functions
Numpy comes with wide range of universal operations which can be used for mathematical operations on arrays. For more, check [Universal Functions](https://numpy.org/doc/stable/reference/ufuncs.html)

In [133]:
# taking square root
 
square_root = np.sqrt(arr)
square_root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [134]:
#calculating exponential

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [136]:
# for fun let's combine two functions

diff = np.max(arr) - np.min(arr)
diff

9

In [137]:
#calculating sin value

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [138]:
#calculating log

np.log(arr)

C:\Users\MANISH~1\AppData\Local\Temp/ipykernel_4264/3205693611.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [142]:
print(np.mean(arr))
print(np.std(arr))

4.5
2.8722813232690143
